### ISSUE TITLE
Update Relationships with ContextBrokerClient update_entity

### ISSUE THREAD

**Issue by dnikolay-ebc** [RWTH-EBC/FiLiP#145]
**Describe the bug**
`ContextBrokerClient -> update_entity` calls `update_or_append_entity_attributes` with `attrs=entity.get_properties()`.
This has the consequence that all relationships, even newly created ones, are ignored.

Is there any reason why `update_entity` is not using `entity.get_attributes()`?

**Comment by tstorek** [comment]
@dnikolay-ebc I can look into but I think that this intended because we are relationships as rather static that should not be updated by bulk operations. Especially, since incomplete updates would accidentally overwrite existing information. If you want to update them you can use one of the other functions provided. I already explained this a little here #92.

**Comment by tstorek** [comment]
@dnikolay-ebc can we close this?

**Comment by tstorek** [comment]
@dnikolay-ebc?

**Comment by tstorek** [comment]
@dnikolay-ebc please, reopen if required!

**Comment by SBlechmann** [comment]
@tstorek 
we had a discussion about the update of relationships. 

In our opinion, relationships are kind of static but we need the ability to adapt them - and not just with the workaround of first deleting them and creating a new one.
This is why we want to remove the protection.

Do you have any reason why we should not pursue this way?

**Comment by SystemsPurge** [comment]
@tstorek is there a reason why each of these functions update_entity, update_entity_relationships and update_entity_properties cannot call update_or_append_entity_attributes with attr=entity.get_attributes, attr=entity.get_relationships and attr=entity.get_properties respectively ?
