### ISSUE TITLE
Mark Quantumleap subscription as deprecated

### ISSUE THREAD

**Issue by tstorek** [RWTH-EBC/FiLiP#215]
In the current release (1.0.0) QuantumLeap no longer supports Subscription as it was just for convenience.

Look here:
https://github.com/orchestracities/ngsi-timeseries-api/pull/748

Therefore, we at least need to catch the error returned and afterwards check version to return a proper Error message.
Even more, give a deprectation warning that the function will be removed in the next Versions of FiLiP.

**Comment by djs0109** [comment]
Besides, we should consider to change the default value of servicepaht to "/" https://github.com/RWTH-EBC/FiLiP/blob/f5f1d9fd4431b68d806e42cd494c00ad887c312e/filip/models/base.py#L86C1-L86C20. QL has already fixed that in the new release
> "Fiware-servicePath was interpreted as python None, from now on, None will be replaced with /. This affects only users that manually injected data, since Orion, assume / when no servicePath is passed.."

**Comment by djs0109** [comment]
As mentioned in #239, this API has been removed in QL1.0.0. After testing the capability with QL1.0.0, all related code and test should be removed. Before that may be create a new tag like `QL0.8.3`

**Comment by djs0109** [comment]
ToDo list:
- [ ] remove subscription endpoint
- [ ] change default servcicepath to "/"
- [ ] support `idPattern` as a query parameter

**Comment by SystemsPurge** [comment]
I could not test whether the id_pattern parameter is working because i am not even certain it is supported in Quantumleap itself. I tried testing it but got inconsistent results.
The subscribe method of the quantumleap client is now blocked by an initial assert statment, mainly so that a well defined error could be caught when testing...
Input on how either issues can be handled in a better way is very welcome.
