### ISSUE TITLE
Dont set the basicConfig of the logging module

### ISSUE THREAD

**Issue by FWuellhorst** [RWTH-EBC/FiLiP#3]
You are doing
```python
logging.basicConfig(level=settings.LOGLEVEL,
                    format='%(asctime)s - FiLiP.%(name)s - %(levelname)s: %('
                           'message)s',
                    datefmt='%Y-%m-%d %H:%M:%S')

```
in `config.py`.
This way, you change the settings for all other modules as well.
the LOGLEVL should be set by the user, not you.

**Comment by tstorek** [comment]
@FWuellhorst you are right that the user should set the loglevel. You can freely change it using the env-file. Nevertheless, I think that it will be good to not reconfigure the basicConfig. Especially, because it would depend on import order. I will try to fix this.

Could your please review afterwards?

**Comment by tstorek** [comment]
This has been fixed!
