### ISSUE TITLE
PATCH request remains in PENDING state / handling of cmdexe

### ISSUE THREAD

**Issue by msc-d1s7fa1eza** [RWTH-EBC/FiLiP#4]
### What is the issue?
When sending a post_command request to the cb and querying the entity state, the set point status may change to PENDING and will not respond to any further requests.

### Proposal
The issue might be related to the cmdexe (see https://github.com/FIWARE/tutorials.IoT-Agent-JSON#southbound-traffic-commands) and the cb expecting to receive an acknowledgement from the device.
As many device might not offer an acknowledgement, this should be optional/settable by the user.
If applied, the cmdexe handling still requires implementation.

**Comment by tstorek** [comment]
Hi,

FiLiP is a client library and not responsible for the inner mechanisms of the Orion Context Broker (OCB) and the IoT-Agent. Hence,
the PENDING state in the OCB will only change if the IoT-Agent receives an ACKNOWLEDGEMENT from the IoT Device on the /cmdexe topic (MQTT-Use Case). This message will then be forwarded to the OCB. The implementation of such message is currently up to the iot-device and not implemented in our library, but probably a good idea for the future.

Nevertheless, we can add an argument to the 'post_command' function and wait for certain delay. A device response otherwise an shoud be raised. I need to figure how this can be a background task because it should rather not block the other functions.

**Comment by tstorek** [comment]
@msc-d1s7fa1eza 

Related to https://github.com/telefonicaid/iotagent-json/issues/585
